url: 'https://hdilab.itu.dk'
# baseurl: '/'
permalink: pretty

title: 'Human Data Interaction Lab'
tagline: Exploring human factors in the conception, use, and understanding of data
description: "The Human Data Interaction Lab focuses on the human factors in the conception, use, and understanding of data. The lab functions as a venue for discussing matters related to human data interaction broadly and invites students and faculty to join forces to better understand these aspects."
site.github.url: 'https://hdilab.itu.dk'
logo: "/images/logo/logo-hdilab.svg"


our_theme_logo:
  mobile: "images/logo/logo-hdilab-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo-hdilab.svg"
  desktop_height: "64px"
  desktop_width: "240px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  data-jams:
    output: true
    sort_by: weight
  people:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "data-jams"
    values:
      layout: "data-jam"
  - scope:
      path: ""
      type: "people"
    values:
      layout: "people"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll/scholar
  - jekyll-seo-tag
  
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:
  style: apa

  last_name: John
  first_name: [Doe, D.]

  locale: en

  sort_by: year,last_name
  order: descending,ascending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bibtex
  # Note: if you have latex math in your bibtex, the latex filter
  # preprocessing may conflict with MathJAX if the latter is enabled.
  # See https://github.com/alshedivat/al-folio/issues/357.
  bibtex_filters: [latex, smallcaps, superscript]
  bibtex_options:
      parse_names: true

  repository: /assets/publications/

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex-details.html
  details_link: ""

  query: "@*"
